export const SET_GAME_DIFFICULTY = 'SET_GAME_DIFFICULTY'

export const SET_GAME_LOCKED = 'SET_GAME_LOCKED'

export const SET_GAME_ENDED = 'SET_GAME_ENDED'

export const SET_GAME_DECK = 'SET_GAME_DECK'

export const SET_GAME_CARD = 'SET_GAME_CARD'

export const SET_GAME_CARDS = 'SET_GAME_CARDS'

export const SET_GAME_CARDS_OPENED = 'SET_GAME_CARDS_OPENED'

export const SET_GAME_CARDS_MATCHED = 'SET_GAME_CARDS_MATCHED'