name: docker

on:
  push:
    branches:
      - master

jobs:

  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    steps:

      - name: build
        run: docker build -t test .


      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v1.1.0
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: memaudio/memaudio-www
      #     tags: latest
      #     tag_with_ref: true
      #     tag_with_sha: true
        