name: main

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install packages
        run: yarn install --pure-lockfile --no-progress

      - name: Build app
        run: yarn build
        env:
          CI: false
        
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
  
  semantic-release:
    name: semantic-release
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build

      - shell: bash
        run: ls -l
        
      - shell: bash
        run: ls -l build
  
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    steps:

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: memaudio/memaudio-www
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
        